language: php

sudo: false

env:
  global:
    - secure: "l+tjr0ODieuGpsjNmlIgNlwB5jCzQeWMLPjnWUIoI2QZlMqgYrW0O1OL0BDyzRmBUWOHcIiJdXxegkaNvMn74c9LfdGYIlVzayZ0nviSQ0GI6OeBuBr04VpFfDtpAeylmtiuzhmu8xfltWQjliXd5rBLjNqS3PtyvxCr8RzNIH1gdGo26fZx/e94sOXodIgupfHgcUclzZKJzgZAbvqCP7tcYW9r4EWwgTRjb1jRPYLbM1srtykp9XLfFV3etydo/80wgAqfa9FEGVtGo4HKnP1e1Bu1QwZizQKAdkGpkCYHmL7qUWrRWkB4dBMOcF0R8tixV9d+V2MaMbzJPbLq3OSDfLP9gdcaPUB1oEjq+RVvUVEwZtWEFrXUgRl4X6C7AZ586mwB8twNrawqdPpiOAkIkl9uyQHxRSVZeR8r+9ZCdZKYLqUyJAvgeXUiQROj7jnVnQADAwuM+4HcTuyjkPEvr6YkCMaCzwIekm+BaeXQurfGeTcpNQXeE6s7Hj3PtzHQjLlADK3paF5hnYDkLp33jW6x7OcmttapyWjhSZlVFHhA3SbfX30gXRUD1tk+ngSnY/8CVVvjJFTF9LdGXoxsWYDQbCb8sSL/7z2v2Yni8w4z2UivoltNoq7F4tqXWG2scqtI+EtolAFw49xtxfG5Kg2a38MRP1awTVRMMT8="
    - secure: "tgWqfTi+W9xsEfJ+rfNoso+tf7dR7qi6j2cmpe/4Vq0vzdHhWhUgFolkEY9N3jynNRShSWsTkQnVtjKxJKX8s8ivye+XZ1L7xmS2gSpRg9+k2QbKwQ5xU1AD9GvbnD9o0MdjtxLGNKQcaHH5hq7Pu2VU9OI3/UQMjHENiTiX4ChkXC8xBL1P/t01VesqmVVZiN6jgIvVDFn5cUUD7IAZ7fc++hm5aDwXIWI7t6smbIhPPLgpU4Opdm0kyohmvfhxL4EWq5qr4Iqy4DfJL/vFWWJFTs/P5SXcLlc+z9KE57iw804SvavKzx4TseJiVb25onKi6xaCHXC+xbtC/0GcwxlGq71hD6UNk/kzH05JznG+gxtVKoQsQ4ySVe+mecABw/rQ4Z5qGpJjnNI+xh2WRtXlo+qjruoYOO0RNRVjNEy3D8nQgBfznQl/cI7Q+iMb4cRuU4AVWZFBH+DeTVKwgY/rOb4WocZqSsYTOfO8IY7dUTZbmVAKg3zJ1GGSjDN3yL+q9qyYzoeTIt2eqqWZbzwAlxuOgWBfWlu7DrGLrQCQGEBkUclKaSFq/X2vRcSuDfJCjY/o305XeM5oW4ViPpknCduSEpKVpp0Y4cBLXdhZ4fv1OwQZVcP6ycLAYZsF3Qj4bce7eaRgIEY3mGY2oy0M/6joJWkDZVQJkkYZI+c="

matrix:
  include:
    - php: 7.1
      env: WITH_LOWEST=true
    - php: 7.1
      env: WITH_LOCKED=true WITH_CS=true WITH_COVERAGE=true
    - php: 7.1
      env: WITH_HIGHEST=true
    - php: 7.2
      env: WITH_LOWEST=true
    - php: 7.2
      env: WITH_LOCKED=true
    - php: 7.2
      env: WITH_HIGHEST=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - source .travis/xdebug.sh
  - xdebug-disable
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then composer remove --dev localheinz/php-cs-fixer-config; fi
  - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest; fi
  - if [[ "$WITH_LOCKED" == "true" ]]; then composer install; fi
  - if [[ "$WITH_HIGHEST" == "true" ]]; then composer update; fi

before_script:
  - mkdir -p $HOME/.php-cs-fixer

script:
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --diff --dry-run --verbose; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

notifications:
  email: false
